### ISSUE TITLE
Image Gallery Support not implemented in UC v0.21?

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#50]
Trying to migrate a project to the UC v0.21
The original project contained an UC Dynamic Reference Parameter of 'Simple Image Gallery' type.
![image](https://cloud.githubusercontent.com/assets/3408226/5094588/266e6bf2-6f30-11e4-9dd2-cf8153678340.png)

However, I no longer see this option in the UC v0.21. 
![image](https://cloud.githubusercontent.com/assets/3408226/5094609/4e86dbc4-6f30-11e4-85d8-def7983904fe.png)

Is there an alternate way to support this?

**Comment by kinow** [comment]
Ping @imoutsatsos , can we close it? I think we can document in the Jenkins Wiki how to create an image gallery like in this job - http://162.243.246.75:8080/job/sample-image-gallery/

WDYT?

**Comment by imoutsatsos** [comment]
I agree we can close this @kinow . The only thing missing by not implementing pictures as a gallery is the pop-up visualization window.  Useful but not necessary. The only question is whether to assign it a post 1.0 label. We may need to hash the pros and cons in a hangout. Thanks!!

**Comment by kinow** [comment]
Let's leave it as it is, and simply not include it in 1.0. We can definitely re-release the image gallery later. Since my only argument was that it would include extra resources (JS, CSS, images), maybe we can work on this issue... maybe finding a way to load it only when using image galleries... 

Let's do another hangout and explore our alternatives :-D (a good excuse for having some good geek talk too)

**Comment by kinow** [comment]
Closing for now. We can re-start this conversation now focusing on the 1.0 version.
