### ISSUE TITLE
Importing a Job with cascade dynamic choice parameter

### ISSUE THREAD

**Issue by Sjoel** [biouno/uno-choice-plugin#62]
The Uno-choice cascade dynamic choice parameter will not load if the job config.xml is imported(probably because of the UUID element in the config.xml). Is there a way to import jobs without losing the parameter?

**Comment by kinow** [comment]
@Sjoel , unfortunately it won't be possible to migrate jobs to this newer version. Even though it would be simple to tell XStream (Jenkins underlying XML serialization library) that the UUID field was removed, we've changed lots of other parts, like the way we store Scripts (Groovy or Scriptler) as sub properties, rather than defining two types of each parameter for each script type.

I'm closing the issue, but I can try to alleviate your work helping with some Groovy-fu if necessary to automate job migration. 

Sorry @Sjoel :-(
