### ISSUE TITLE
DB Based choice provider

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#63]
There is a group that has reported the availability of a database based choice provider.
https://issues.jenkins-ci.org/browse/JENKINS-24274

![image](https://cloud.githubusercontent.com/assets/3408226/5303531/46d65186-7bb8-11e4-9a9c-86ac010c5af2.png)

The code is for extending the [Extensible Choice Parameter plugin](https://wiki.jenkins-ci.org/display/JENKINS/Extensible+Choice+Parameter+plugin) but it seems that this feature would also be a great addition to the uno-choice parameter types. What do you think? Would it be worth contacting the developer and see if they would like to contribute to uno-choice?

**Comment by kinow** [comment]
Commented in the issue - https://issues.jenkins-ci.org/browse/JENKINS-24274

Seems like there has been no reply of the plug-in maintainer, so we may have to try our best at a new implementation of a similar parameter type.

**Comment by tduchateau** [comment]
Comment added ;-)
I'll keep you posted as soon as the fork is available.

**Comment by kinow** [comment]
Yay, thanks for the quick response @tduchateau. Would you mind if we shamelessly copied your code to this plug-in too? :-) All credits will go to you.

**Comment by tduchateau** [comment]
> Would you mind if we shamelessly copied your code to this plug-in too?

Of course! Also feel free to improve or even rewrite it! ;-)

**Comment by kinow** [comment]
Thanks @tduchateau ! We'll make sure to include the credits and, in case we find ways to improve it, we'll definitely ping you to see if there's some interest in re-using the code :-)

**Comment by tduchateau** [comment]
Hey!

PR submitted: https://github.com/jenkinsci/extensible-choice-parameter-plugin/pull/8 ;-)

**Comment by kinow** [comment]
Awesome @tduchateau ! And already includes French translation :-) Thanks a lot!!!

@imoutsatsos I'm not really sure how to integrate this PR in unochoice right now, without changing many parts of the code. Let's push it to 1.1 or maybe a 2.0 release?

I never read Extensible Choice Parameter Plug-in's code. If I had read it before, I'd probably copy their extension point for ChoiceListProvider... so instead of only supporting Scripts, we could support Scripts, Text Areas, or other custom choice list providers. 

The easiest path, IMO, is release 1.0 as-is, and then create a new parameter type for DB connections. But it would have settings per job, and not global settings.

Thoughts?

**Comment by imoutsatsos** [comment]
Agree. This should be a post 1.0 feature. Settings per job is the way to go too. We can think about the implementation details. Thanks @kinow  and @tduchateau !

**Comment by kinow** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-28736
