### ISSUE TITLE
When UC options get filtered the first option does not cacscade value changes

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#70]
Happy new year @kinow ! Hope 2015 produces a record deficit of bugs!

This one does not get logged towards 2015 since I've detected it before going on holidays ;-)

When applying a filter to uno-choice options the first value on the resulting list does not trigger cascade changes.
See http://162.243.246.75:8080/job/issue-70

In or famous state-cities example when the option list contains a single state, I can't cascade it's change to update the cities.

![image](https://cloud.githubusercontent.com/assets/3408226/5616060/e09b0b70-94ce-11e4-8e0e-41110cad597e.png)

Originally I thought that this bug only affected a list that filtering reduced to a single value, but I think that this happens even when the list has moire than one values selected by the filter (try this example).

![image](https://cloud.githubusercontent.com/assets/3408226/5617289/01010ee4-94db-11e4-858c-6eb33d5da7df.png)

Hope you are well refreshed after the holidays!
best regards
Ioannis

**Comment by kinow** [comment]
Happy new year @imoutsatsos !!! 

Hmmm, interesting issue... maybe I've overseen it during our tests, because I think I remember having this problem somewhere in the past. 

I'll finish some development cycle on other tools and will get back at BioUno development within some days. Stay tuned for a wave of issue fixes (hopefully fixes + tests) :)

**Comment by kinow** [comment]
Added a simple propagation event, so that when the filter gets updated (i.e. the user enters a key in the filter input box) it tells the parameter that it changed. 

We need to test if this new event is not interfering with other elements. But I think it will work. We don't have tests covering event propagation yet.

**Comment by imoutsatsos** [comment]
This seems to work as expected now. I have not observed any other issues, but I'm still doing some additional testing with a bunch of projects that I have migrated to v0.23. Thanks for completing another 1.0 milestone @kinow !

**Comment by kinow** [comment]
Yay! Thanks @imoutsatsos ! With every issue we get closer to 1.0! \o/

**Comment by kinow** [comment]
Seems to be working now in 1.0. Please feel free to re-open an issue in https://issues.jenkins-ci.org/ with component name active-choices-plugin in case the issue persists. Thanks!
